language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - flake8 nestdeviceaccess/
  - pytest nestdeviceaccess/test_nestdeviceaccess.py
  - coverage run -m pytest nestdeviceaccess/test_nestdeviceaccess.py
after_success:
  - bash <(curl -s https://codecov.io/bash)